spring:
  application:
    name: chagok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/parkinghub
    username: valetparker
    password: valetparker


server:
  servlet:
    encoding:
      force: true
jwt:
  secret: LH9QZL8upsPBfuDY+Dkb1kT9DZIIUSuA2u4O6Lfi3mkEfeWtETpVTcR/8SMZdJWn/xNTuCQBE6rBvDXgnVmscQ==
  expiration: 1800000
  refresh-expiration: 604800000

kakaopay:
  secret-key: DEV83DBF4CA9253457F361D494F1E9F3DE56682C
  cid: TC0ONETIME
  redirect-url-success: http://localhost:8080/kakaopay/success
  redirect-url-cancel: http://localhost:8080/kakaopay/cancel
  redirect-url-fail: http://localhost:8080/kakaopay/fail
