#spring.application.name=payment-service
server:
  port: 8099

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: valetparker-payment-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/parkinghub
    username: valetparker
    password: valetparker
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ???
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

# ?????
kakaopay:
  secret-key: DEV83DBF4CA9253457F361D494F1E9F3DE56682C
  cid: TC0ONETIME
  redirect-url-success: http://localhost:8000/kakaopay/success
  redirect-url-cancel: http://localhost:8000/kakaopay/cancel
  redirect-url-fail: http://localhost:8000/kakaopay/fail